### ISSUE TITLE
Is there any hope to support desktop version 2.2?

### ISSUE THREAD

**Issue by xushet** [grandsilence/telegram-font-patcher-csharp#2]
Yes, the desktop has been officially updated
![QQ截图20200814231941](https://user-images.githubusercontent.com/34502902/90265274-ec50f780-de84-11ea-93ee-989c5315d4eb.png)

**Comment by grandsilence** [comment]
HI. I've patched 2.2 without any issues using [previous version from Releases](https://github.com/grandsilence/telegram-font-patcher-csharp/releases/tag/v2.1.2). Do you have any issues using it?
